import { NextResponse } from 'next/server';
import { z } from 'zod';
import { adminDb } from '@/lib/firebase-admin';
import { verifyParentFromRequest } from '@/lib/auth';
import { serializeTimestamp } from '@/lib/utils';
const choreSchema=z.object({childId:z.string().min(1),title:z.string().min(1),description:z.string().optional(),rewardCoins:z.number().int().positive(),frequency:z.enum(['one-time','daily','weekly'])});
async function getFamilyId(uid:string){const parentSnap=await adminDb.collection('parents').doc(uid).get();const familyId=parentSnap.data()?.familyId;if(!familyId) throw new Error('Parent account is not initialized');return familyId as string;}
export async function GET(request:Request){try{const decoded=await verifyParentFromRequest(request);const familyId=await getFamilyId(decoded.uid);const {searchParams}=new URL(request.url);const childId=searchParams.get('childId');let query:any=adminDb.collection('families').doc(familyId).collection('chores').where('active','==',true);if(childId) query=query.where('childId','==',childId);const snapshot=await query.get();const chores=snapshot.docs.map((doc:any)=>{const data=doc.data();return {id:doc.id,...data,createdAt:serializeTimestamp(data.createdAt)};});return NextResponse.json({chores});}catch(error){const message=error instanceof Error?error.message:'Failed to fetch chores';return NextResponse.json({error:message},{status:401});}}
export async function POST(request:Request){try{const decoded=await verifyParentFromRequest(request);const familyId=await getFamilyId(decoded.uid);const body=await request.json();const input=choreSchema.parse(body);const childSnap=await adminDb.collection('families').doc(familyId).collection('children').doc(input.childId).get();if(!childSnap.exists) return NextResponse.json({error:'Child not found'},{status:404});const choreRef=adminDb.collection('families').doc(familyId).collection('chores').doc();await choreRef.set({familyId,childId:input.childId,title:input.title,description:input.description??'',rewardCoins:input.rewardCoins,frequency:input.frequency,active:true,createdAt:new Date()});return NextResponse.json({id:choreRef.id});}catch(error){const message=error instanceof Error?error.message:'Failed to create chore';return NextResponse.json({error:message},{status:400});}}
