import { NextResponse } from 'next/server';
import { z } from 'zod';
import { adminDb } from '@/lib/firebase-admin';
import { verifyParentFromRequest } from '@/lib/auth';
import { generateAccessCode, serializeTimestamp } from '@/lib/utils';
import { hashPin, isValidPin } from '@/lib/security';
const childSchema=z.object({name:z.string().min(1),displayName:z.string().min(1).optional(),age:z.number().int().min(3).max(18),avatar:z.string().optional(),pin:z.string().regex(/^\d{4}$/)});
async function getFamilyId(uid:string){const parentSnap=await adminDb.collection('parents').doc(uid).get();const familyId=parentSnap.data()?.familyId;if(!familyId) throw new Error('Parent account is not initialized');return familyId as string;}
export async function GET(request:Request){try{const decoded=await verifyParentFromRequest(request);const familyId=await getFamilyId(decoded.uid);const snapshot=await adminDb.collection('families').doc(familyId).collection('children').orderBy('createdAt','desc').get();const children=snapshot.docs.map(doc=>{const data=doc.data();return {id:doc.id,...data,createdAt:serializeTimestamp(data.createdAt),updatedAt:serializeTimestamp(data.updatedAt)};});return NextResponse.json({children,familyId});}catch(error){const message=error instanceof Error?error.message:'Failed to fetch children';return NextResponse.json({error:message},{status:401});}}
export async function POST(request:Request){try{const decoded=await verifyParentFromRequest(request);const familyId=await getFamilyId(decoded.uid);const body=await request.json();const input=childSchema.parse(body);if(!isValidPin(input.pin)) return NextResponse.json({error:'PIN must be 4 digits'},{status:400});let accessCode=generateAccessCode();while((await adminDb.collection('childAccessCodes').doc(accessCode).get()).exists){accessCode=generateAccessCode();}const childRef=adminDb.collection('families').doc(familyId).collection('children').doc();const now=new Date();await adminDb.runTransaction(async tx=>{tx.set(childRef,{familyId,name:input.name,displayName:input.displayName??input.name,age:input.age,avatar:input.avatar??'fox',accessCode,pinHash:hashPin(input.pin),needsPersonalization:true,balance:0,streak:0,saveCoins:0,spendCoins:0,shareCoins:0,totalCoinsEarned:0,totalChoresCompleted:0,learningProgress:[],createdAt:now,updatedAt:now});tx.set(adminDb.collection('childAccessCodes').doc(accessCode),{familyId,childId:childRef.id,createdAt:now});});return NextResponse.json({id:childRef.id,familyId,accessCode});}catch(error){const message=error instanceof Error?error.message:'Failed to create child';return NextResponse.json({error:message},{status:400});}}
